### ISSUE TITLE
Add info to doc about webdriver.io

### ISSUE THREAD

**Issue by sipayRT** [gemini-testing/testplane#14]

**Comment by tavriaforever** [comment]
1. Add examples for tests with code
2. Make config from example shorter
3. Add quick start with saucelabs or another selenium service
4. Add info about tests API (webdriver.io link)

**Comment by tarmolov** [comment]
5. Add custom command example.
6. Add guide about writing plugins.

**Comment by florinalex1984** [comment]
Hi, any updates on this?

**Comment by DudaGod** [comment]
@sipayRT is it still relevant?

**Comment by sipayRT** [comment]
yep

**Comment by Angelliu888** [comment]
Hi, I am angel, I want to know more about Gemini global

**Comment by sipayRT** [comment]
fixed with  https://testplane.io/
