### ISSUE TITLE
Не до конца страницы делается скриншот

### ISSUE THREAD

**Issue by IrinaDydy** [gemini-testing/testplane#619]
Добрый день!

Иногда, не до конца страницы делается скриншот.
Пример: 
![image](https://user-images.githubusercontent.com/44712585/140706837-f6f5d14f-5186-4fd0-bf03-da7d8502a482.png)

С чем может быть связанно?

**Comment by DudaGod** [comment]
Привет.

Довольно сложно сказать в чем проблема имея на руках только скриншот без какого либо минимального кейса для воспроизведения. Но предположу, что проблема связанна с тем как подгружается данная страница. Возможно присутствует какая-то ленивая загрузка данных. В итоге получается что в некоторых случаях данные все успели загрузится перед выполнением скриншота, а в некоторых только часть.

**Comment by IrinaDydy** [comment]
Спасибо за ответ! 
Проблема плавающая, по этому сложно предоставить кейс для воспроизведения, но попробую уточнить по поводу ленивой загрузки данных.
