### ISSUE TITLE
Не работает ховер, если страницу нужно просколлить

### ISSUE THREAD

**Issue by AdelFattakhova** [gemini-testing/testplane#779]
Привет! Не уверена, что ишью к вам, а не к webdriverio, но пока попробую сюда, может быть подскажете)

Проблема следующая:

1. нужно проверить состояние какого-либо элемента на ховер
2. нужный элемент находится вне вьюпорта, до него нужно доскроллить
3. на скриншоте с этого элемента – элемент в обычном состоянии, без ховера

Пример:

```js
it('test', async ({ browser }) => {
    await browser.url('https://translate.yandex.ru');

    await browser.assertView('doc', '.header-nav-link:nth-child(2)');
    await browser.$('.header-nav-link:nth-child(2)').moveTo();
    await browser.assertView('doc-hovered', '.header-nav-link:nth-child(2)', {
      screenshotDelay: 200
    });
    await browser.$('a[href*="0488000000"]').scrollIntoView();
    await browser.$('a[href*="0488000000"]').moveTo();
    await browser.assertView('footer-text-hovered', 'a[href*="0488000000"]', {
      screenshotDelay: 200
    });
});
```

Получается, что ссылка из навигации в шапке скриншотится как нужно, с ховером. А та, что в футере, без ховера, хотя должна:

<img width="443" alt="Снимок экрана 2023-07-31 в 17 42 56" src="https://github.com/gemini-testing/hermione/assets/25532966/45df8be5-dfac-4072-af24-e8c0b119d39c">

Вопрос: как это можно починить?

**Comment by DudaGod** [comment]
Привет.

А в каком браузере запускаешь и с какими настройками?
Проверил на chrome@101 и получил следующий результат:

<img width="565" alt="Screenshot 2023-08-07 at 13 06 12" src="https://github.com/gemini-testing/hermione/assets/5900697/6d8f437e-8acb-4a1b-bc96-c83191be9392">

**Comment by AdelFattakhova** [comment]
Браузер Chrome. Судя по логам, 115 версия. Или может я не там смотрю

<img width="450" alt="image" src="https://github.com/gemini-testing/hermione/assets/25532966/5df1d0ad-9f19-45ad-a524-9823701278ce">

Настройки вот такие:

```js
{
  gridUrl: 'http://localhost:4444/wd/hub',

  compositeImage: true,
  screenshotsDir: 'references',
  sessionsPerBrowser: 5,

  tolerance: 5,
  antialiasingTolerance: 4,

  browsers: {
    chrome: {
      retry: 5,
      automationProtocol: 'devtools',
      desiredCapabilities: {
        browserName: 'chrome',
        'goog:chromeOptions': {
          args: [
            'headless',
            '--hide-scrollbars'
          ]
        }
      },
      windowSize: {
        width: 1440,
        height: 900
      }
    },
  }
}
```

**Comment by DudaGod** [comment]
Проблему воспроизвел. Действительно, при запуске теста с использованием `devtools` скриншот с текстом "Переводите в Яндекс Браузере" снимается как будто без ховера.

Постараюсь подебажить на днях.

**Comment by denisbalyko** [comment]
Похожая проблема после обновления на 7.4.1 версию (и вероятно на webdriverio 8) выглядит будто метод `moveTo` не триггерит `mouseover` на элементе.

**Comment by denisbalyko** [comment]
> Похожая проблема, после обновления на 7.4.1 версию (и вероятно на webdriverio 8) выглядит будто метод `moveTo` не триггерит `mouseover` на элементе.

Сам написал, сам решил проблему, сам отвечу (похоже у меня другой кейс), но проблема была в неверно выставленом `mobileEmulation`

**Comment by sipayRT** [comment]
> > Похожая проблема, после обновления на 7.4.1 версию (и вероятно на webdriverio 8) выглядит будто метод `moveTo` не триггерит `mouseover` на элементе.
> 
> Сам написал, сам решил проблему, сам отвечу (похоже у меня другой кейс), но проблема была в неверно выставленом `mobileEmulation`

привет

а покажи, плз, дифф твоих настроек (как не работало и что изменил, чтобы заработало). Думаю, что кому-то в истории это точно пригодится

**Comment by denisbalyko** [comment]
Помимо обновления версии мне нужно было оторвать пакет `@какое-то-название-int/frontend-hermione-config`, в нём был `get-browsers`, эти настройки дополнялись на уровне нашего проекта. Из-за бага всем браузерам доставился `mobileEmulation` в тч и 'linux-chrome'.
Вероятно, это крайне специфичная история. Но если не работает `moveTo` в том числе стоит проверить настройки браузера.

**Comment by DudaGod** [comment]
Fixed in:
- testplane@8.11.3
- hermione@8.9.3
- hermione@7.5.7
