### ISSUE TITLE
Add a handy way to screenshot the viewport

### ISSUE THREAD

**Issue by sipayRT** [gemini-testing/testplane#932]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/gemini-testing/hermione/blob/master/CONTRIBUTING.md))

### Describe the user story

for now for testing viewport view you need to composite options for `assertView` command:

```js
await browser.assertView('check-viewport', 'body', {
    allowViewportOverflow: true,
    compositeImage: false
});
```

### Describe the solution you'd like

There must be a more convenient way. For example, a new command with a preset from the example above

```js
await browser.assertViewViewport('check-viewport'); // the command name is discussable
```

**Comment by Kabir-Ivan** [comment]
Solved by https://github.com/gemini-testing/testplane/pull/988
