### ISSUE TITLE
В тесте недоступно поле browserId

### ISSUE THREAD

**Issue by bolkonya** [gemini-testing/testplane#937]
### Verify latest release

- [ ] I verified that the issue exists in the latest Hermione release

### Hermione version

8.9.3

### Last Hermione version that worked

7.5.5

### Reproduction steps

Попытаться получить значение browser.executionContext.browserId

Раньше значение было доступно через this.currentTest.browserId

### Actual Behavior

Такого поля нет в типе executionContext

### Expected Behavior

Поле указано в типе и доступно для чтения - как и следует из документации в разделе https://github.com/gemini-testing/testplane/tree/hermione/8.9.3?tab=readme-ov-file#execution-context

### Which Node.js version are you using?

20.10.0

**Comment by DudaGod** [comment]
Привет. А можешь прислать пример воспроизведения?

Я набросал такой тест с использованием hermione@8.9.3:
```
it('test', async ({browser}) => {
    console.log('browser.executionContext:', browser.executionContext.browserId);
});
```

И получил корректное название браузера.

**Comment by bolkonya** [comment]
Да, поле действительно доступно для чтения, я не совсем правильно описал ишью: проблема именно с типизацией executionContext, её нужно доуточнить

```
executionContext: (RunnerTest | RunnerHook) & {
            hermioneCtx: {
                assertViewResults: Array<AssertViewResult>;
            };
            ctx: {
                browser: WebdriverIO.Browser;
                currentTest: RunnerTest;
            };
        };
```

**Comment by DudaGod** [comment]
> Да, поле действительно доступно для чтения, я не совсем правильно описал ишью: проблема именно с типизацией executionContext, её нужно доуточнить

Да, с этим есть проблема. Поправил в hermione@8.9.4. Проверь, пожалуйста.

**Comment by bolkonya** [comment]
Да, теперь типы на месте, спс! Приятным бонусом полечился еще и тип currentTest, благодаря чему hermione-allure больше не расходится в типах с ним.

Есть теперь вопрос по поводу TestFunctionCtx - давай я вынесу в отдельное обсуждение его
