### ISSUE TITLE
Пропала типизация describe/it и т.п.

### ISSUE THREAD

**Issue by bolkonya** [gemini-testing/testplane#940]
### Verify latest release

- [ ] I verified that the issue exists in the latest Hermione release

### Hermione version

hermione/8.9.4

### Last Hermione version that worked

8.9.3

### Reproduction steps

https://github.com/bolkonya/hermione-playground

Установить зависимости и проверить типы 

### Actual Behavior

describe и it имеют тип any

### Expected Behavior

они типизированы, как раньше - describe: SuiteDefinition, it: TestDefinition

### Which Node.js version are you using?

20.10.0

**Comment by DudaGod** [comment]
Починил в hermione@8.9.5. Спасибо, что обратил внимание. Я тестировал с помощью линков и не заметил проблемы.
