### ISSUE TITLE
Add ability to rerun all failed tests

### ISSUE THREAD

**Issue by sipayRT** [gemini-testing/testplane#953]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/gemini-testing/hermione/blob/master/CONTRIBUTING.md))

### Describe the user story

now, in order to restart only the failed tests, I need to use 2 plugins:
1. https://github.com/gemini-testing/json-reporter to get the test results with json format
2. https://github.com/gemini-testing/testplane-test-filter to run tests only specified in the json-file

### Describe the solution you'd like

how it can work:
1. run all tests in CI
2. get the json-output with failed tests
3. rerun only tests specified in the json-output (only failed)

**Comment by Kabir-Ivan** [comment]
Solved by https://github.com/gemini-testing/testplane/pull/973
