### ISSUE TITLE
Update webdriverio package

### ISSUE THREAD

**Issue by vitaly-kiselev-qa** [gemini-testing/testplane#957]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/gemini-testing/hermione/blob/master/CONTRIBUTING.md))

### Describe the user story

We have the issue with the `browser.mock` method. 

Sometimes it just do nothing and our tests fail.

I've noticed that the [latest implemetation of the method](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/mock.ts) significatly differs from [current](https://github.com/webdriverio/webdriverio/blob/v8.20.1/packages/webdriverio/src/commands/browser/mock.ts).
I hope that the new implementation does not have this issue.

### Describe the solution you'd like

The current version of the `webdriverio` package is `8.21.0`.
Please, update it to the latest one.

**Comment by Kabir-Ivan** [comment]
Solved by https://github.com/gemini-testing/testplane/pull/989
