### ISSUE TITLE
Ссылка на документацию в репозитории

### ISSUE THREAD

**Issue by readyyyk** [gemini-testing/testplane#967]
### Describe the user story

При попытках работы с новой библиотекой я искал ее документацию. Не справившись с этой задачей я копался в исходниках, типах и двух не совсем обширных примерах.

В то время как сайт с документацией существует.

### Describe the solution you'd like

Я, как пользователь библиотеки, хотел бы увидеть ссылку на сайт (testplane.io)
- в репозитории самой библиотеки (возможно сразу на роут /docs)
- на странице организации
- на странице репозитория документации

**Comment by shadowusr** [comment]
@readyyyk

Спасибо! Ссылки на сайт добавили в README и About.

---

Thanks! We've added links to https://testplane.io to the README file and the About section.
