### ISSUE TITLE
mocha оверрайдит типы jest, начиная с testplane релизов

### ISSUE THREAD

**Issue by jehy** [gemini-testing/testplane#996]
### Verify latest release

- [X] I verified that the issue exists in the latest Hermione release

### Reproduction steps

1. используем проект с джест и гемионой
2. всё падает, так как подтягиваемые типы из hermione->mocha перекрывают типы jest для функций с тем же названием

### Actual Behavior

всё падает

### Expected Behavior

хочется чтобы не падало

### Which Node.js version are you using?

20

**Comment by jehy** [comment]
вроде правится в https://github.com/gemini-testing/testplane/pull/995/files - влейте, пожалуйста.

**Comment by KuznetsovRoman** [comment]
Привет. `jest` и `hermione` тесты находятся в разных файлах? Для `jest` используете глобальные `it` / `describe` / ... или импортируете в каждом файле?

**Comment by KuznetsovRoman** [comment]
> 1. тесты находятся в разных файлах
> 2. используем глобальные

В таком случае я не вижу иного варианта, кроме как использовать два различных файла `tsconfig.json`.
Тогда можно будет ограничить `compilerOptions.types` и указать так, чтобы для `testplane` тестов использовались типы из `testplane`, а для `jest` - типы из `jest`. Например, вот так будет выглядеть `compilerOptions` в `tsconfig.json` для `testplane` тестов:
```json
    "compilerOptions": {
        "types": [
            "testplane"
        ]
    }
```

**Comment by jehy** [comment]
Хмм. Такс

1. Извините, что гнал, понял, что глобалы без моки в прод зависимостях не будут работать, и иначе не сделаешь.
2. Да, у нас в текущей версии есть compilerOptions - но только для гермионы
3. Судя по всему, в текущей версии у нас выходит, что приоритет у jest типов, а конкретно для директории гермиона тестов типы оверрайдятся на её. А при обновлении на testplane, видимо, идёт приоритет загрузки по алфавитному порядку имени пакета, и резолв происходит обратный.
4. Если для гермиона тестов, которые все лежат в одной директории, легко написать types, и там в целом не будет ничего не хватающего, то написать их для всего остального проекта (где, как принято, тесты лежат рядом с кодом) - весьма затруднительно, поскольку там не только node и jest, но и куча всего другого... Да и явно держать там всю огромную перепись типов не хочется...

В общем, забавная бага из-за смены алфавитного порядка, видимо. Не знаю, можете ли вы её как-то получить со своей стороны, но было бы здорово добавить её в мануал по миграции - наверняка не мы одни на это наступим. А для нас это видимо пока блокер...

... Интересно, а можно продолжать публиковать testplane в пакете hermione? Это бы решило проблему :)

**Comment by KuznetsovRoman** [comment]
> В общем, забавная бага из-за смены алфавитного порядка, видимо. Не знаю, можете ли вы её как-то полечить со своей стороны, но было бы здорово добавить её в мануал по миграции - наверняка не мы одни на это наступим. А для нас это видимо пока блокер...

Да, в гайд по миграции нужно это добавить. Полечить со своей стороны - сможем, но, к сожалению, только в `testplane@9` - в следующей версии мы планируем перестать использовать глобальные декларации по умолчанию, а предоставлять их отдельным пакетом тем, кому это нужно, но это мажор, поэтому только в `testplane@9`: https://github.com/gemini-testing/testplane/issues/854#issuecomment-2288386705

**Comment by jehy** [comment]
Да, звучит как решение, спасибо!

**Comment by KuznetsovRoman** [comment]
> Если для гермиона тестов, которые все лежат в одной директории, легко написать types, и там в целом не будет ничего не хватающего, то написать их для всего остального проекта (где, как принято, тесты лежат рядом с кодом) - весьма затруднительно

Если в корне проекта лежит папка `src` с исходниками, а гермиона-тесты лежат в отдельной директории, то при переходе на `testplane` в этой отдельной директории с гермиона-тестами можно описать следующий `tsconfig.json`:
```json
{
    "compilerOptions": {
        "types": [
            "testplane"
        ]
    }
}
```
Чтобы в папке `src` были именно `jest` тайпинги, можно сделать следующее:
- По пути, например, `src/types/jest.d.ts` создаем файл:
```ts
/// <reference types="jest" />
```
- В `tsconfig.json` в корне проекта вставляем этот путь в `include` секцию до `src`. Например, вот так:
```json
{
    "compilerOptions": {
        "include": ["./src/types/jest.d.ts", "./src"],
    }
}
```
Теперь в директории `src` будут использоваться именно `jest` тайпинги у `it`, `describe`, `expect`
